<?php

/**
 * @file
 * Provide extended access control for forums.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\taxonomy\TermInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function thunder_forum_access_form_forum_overview_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add 'configure access' operation link to all terms.
  foreach (Element::children($form['terms']) as $key) {
    if (isset($form['terms'][$key]['#term'])) {
      $form['terms'][$key]['operations']['#links']['thunder_forum_access']['title'] = t('configure access');
      $form['terms'][$key]['operations']['#links']['thunder_forum_access']['url'] = Url::fromRoute('entity.taxonomy_term.thunder_forum_access', ['taxonomy_term' => $form['terms'][$key]['#term']->id()]);
      $form['terms'][$key]['operations']['#links']['thunder_forum_access']['query'] = \Drupal::destination()->getAsArray();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for taxonomy_term entities.
 */
function thunder_forum_access_taxonomy_term_insert(TermInterface $entity) {
  /** @var \Drupal\thunder_forum_access\Access\ForumAccessRecordStorageInterface $forum_access_storage */
  $forum_access_storage = \Drupal::service('thunder_forum_access.forum_access_record_storage');

  // Insert forum access record.
  $forum_access_storage->termInsert($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for taxonomy_term entities.
 */
function thunder_forum_access_taxonomy_term_delete(TermInterface $entity) {
  /** @var \Drupal\thunder_forum_access\Access\ForumAccessRecordStorageInterface $forum_access_storage */
  $forum_access_storage = \Drupal::service('thunder_forum_access.forum_access_record_storage');

  // Delete forum access record.
  $forum_access_storage->termDelete($entity);
}

/**
 * Implements hook_ENTITY_TYPE_presave() for taxonomy_term entities.
 */
function thunder_forum_access_taxonomy_term_presave(TermInterface $entity) {
  /** @var \Drupal\thunder_forum_access\Access\ForumAccessRecordStorageInterface $forum_access_storage */
  $forum_access_storage = \Drupal::service('thunder_forum_access.forum_access_record_storage');

  // Perform pre-save operations.
  $forum_access_storage->termPreSave($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update() for taxonomy_term entities.
 */
function thunder_forum_access_taxonomy_term_update(TermInterface $entity) {
  /** @var \Drupal\thunder_forum_access\Access\ForumAccessRecordStorageInterface $forum_access_storage */
  $forum_access_storage = \Drupal::service('thunder_forum_access.forum_access_record_storage');

  // Update forum access record.
  $forum_access_storage->termUpdate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for user entities.
 */
function thunder_forum_access_user_delete(AccountInterface $entity) {
  /** @var \Drupal\thunder_forum_access\Access\ForumAccessRecordStorageInterface $forum_access_storage */
  $forum_access_storage = \Drupal::service('thunder_forum_access.forum_access_record_storage');

  // Delete forum access records.
  $forum_access_storage->userDelete($entity);
}

/**
 * Implements hook_thunder_forum_access_records_change().
 */
function thunder_forum_access_thunder_forum_access_records_change(array $tids) {
  $tags = [];

  // Build list of cache tags for affected forum taxonomy terms.
  foreach ($tids as $tid) {
    $tags[] = 'taxonomy_term:' . $tid;
  }

  // Invalidate cache records for affected forum taxonomy terms.
  Cache::invalidateTags($tags);
}
