# Schema for the configuration files of the Thunder Notify module.

thunder_notify.source.*:
  type: config_object
  label: 'Notification source'
  mapping:
    message:
      type: text
      label: 'Message to send in a notification'

# thunder_notify.type.{type}.{category}:
thunder_notify.type.*.*:
  type: config_object
  label: 'Categorized notification type'
  mapping:
    subject:
      type: label
      label: 'Subject'
    message:
      type: text
      label: 'Message'
