# Schema for the configuration files of the Thunder Notify module.

thunder_notify.settings:
  type: config_object
  mapping:
    cron_access_key:
      type: string
      label: 'Cron access key'
    queue:
      label: 'Queue'
      type: mapping
      mapping:
        limit:
          type: integer
          label: 'Maximum number of items to process'
    notification_types:
      label: 'Notification types'
      type: sequence
      sequence:
        type: string
        label: 'Notification type'

thunder_notify.source.*:
  type: config_object
  label: 'Notification source'
  mapping:
    message:
      type: text
      label: 'Message to send in a notification'

# thunder_notify.type.{type}.{category}:
thunder_notify.type.*.*:
  type: config_object
  label: 'Categorized notification type'
  mapping:
    subject:
      type: label
      label: 'Subject'
    message:
      type: text
      label: 'Message'
