# Schema for the configuration files of the Thunder Notify module.

thunder_notify.source.*:
  type: config_object
  label: 'Notification source'
  mapping:
    message:
      type: text
      label: 'Message to send in a notification'
thunder_notify.type.*:
  type: config_object
  label: 'Notification type'
  mapping:
    subject:
      type: label
      label: 'Notification subject'
    message:
      type: text
      label: 'Message to send in a notification'
